-- =============================================
-- Stored Procedure: sp_Employees_CRUD
-- Purpose: Handle CRUD operations for Employees table
-- Created: 2026-02-23
-- =============================================

USE [YourDatabaseName] -- Replace with your actual database name
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[sp_Employees_CRUD]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[sp_Employees_CRUD]
GO

CREATE PROCEDURE [dbo].[sp_Employees_CRUD]
    -- Action Parameter
    @Action NVARCHAR(20), -- INSERT, UPDATE, DELETE, GETBYID, GETALL
    
    -- Id Parameter (for UPDATE, DELETE, GETBYID)
    @Id INT = NULL,
    
    -- Employee Basic Information
    @EmployeeCode NVARCHAR(20) = NULL,
    @Serviceproviderid NVARCHAR(20) = NULL,
    @FirstName NVARCHAR(100) = NULL,
    @LastName NVARCHAR(100) = NULL,
    @FullName NVARCHAR(200) = NULL,
    @Email NVARCHAR(256) = NULL,
    @PhoneNumber NVARCHAR(20) = NULL,
    @AlternatePhone NVARCHAR(20) = NULL,
    @ProfileImage NVARCHAR(1000) = NULL,
    @DateOfBirth DATE = NULL,
    @Gender NVARCHAR(20) = NULL,
    
    -- Address Information
    @Address NVARCHAR(500) = NULL,
    @City NVARCHAR(100) = NULL,
    @State NVARCHAR(100) = NULL,
    @ZipCode NVARCHAR(20) = NULL,
    @Country NVARCHAR(100) = NULL,
    
    -- Employment Information
    @EmployeeType NVARCHAR(50) = NULL,
    @Department NVARCHAR(100) = NULL,
    @Position NVARCHAR(100) = NULL,
    @JobTitle NVARCHAR(100) = NULL,
    @ReportsTo INT = NULL,
    @HireDate DATE = NULL,
    @StartDate DATE = NULL,
    @EndDate DATE = NULL,
    @ProbationEndDate DATE = NULL,
    
    -- Schedule Information
    @WorkSchedule NVARCHAR(MAX) = NULL,
    @DefaultStartTime TIME = NULL,
    @DefaultEndTime TIME = NULL,
    @WeeklyHours DECIMAL(5,2) = NULL,
    @IsFlexibleSchedule BIT = NULL,
    
    -- Payment Information
    @PayType NVARCHAR(20) = NULL,
    @PayRate DECIMAL(10,2) = NULL,
    @Currency NVARCHAR(10) = NULL,
    @BankAccountNumber NVARCHAR(50) = NULL,
    @BankRoutingNumber NVARCHAR(50) = NULL,
    
    -- Skills and Qualifications
    @Skills NVARCHAR(MAX) = NULL,
    @Certifications NVARCHAR(MAX) = NULL,
    @Specializations NVARCHAR(MAX) = NULL,
    @Languages NVARCHAR(500) = NULL,
    @YearsOfExperience INT = NULL,
    @Bio NVARCHAR(1000) = NULL,
    
    -- Service Assignments
    @AssignedServices NVARCHAR(MAX) = NULL,
    @AssignedLocations NVARCHAR(MAX) = NULL,
    @MaxDailyAppointments INT = NULL,
    @CanAcceptNewClients BIT = NULL,
    
    -- User and Role Information
    @UserId INT = NULL,
    @Role NVARCHAR(50) = NULL,
    @Permissions NVARCHAR(MAX) = NULL,
    @CanManageOwnSchedule BIT = NULL,
    @CanViewReports BIT = NULL,
    @CanManageClients BIT = NULL,
    @LastLoginDate DATETIMEOFFSET = NULL,
    
    -- Verification and Background Check
    @IdDocumentUrl NVARCHAR(1000) = NULL,
    @IdDocumentVerified BIT = NULL,
    @BackgroundCheckStatus NVARCHAR(50) = NULL,
    @BackgroundCheckDate DATE = NULL,
    
    -- Emergency Contact
    @EmergencyContactName NVARCHAR(200) = NULL,
    @EmergencyContactPhone NVARCHAR(20) = NULL,
    @EmergencyContactRelation NVARCHAR(50) = NULL,
    
    -- Status and Notes
    @Status NVARCHAR(50) = NULL,
    @StatusReason NVARCHAR(500) = NULL,
    @Notes NVARCHAR(MAX) = NULL,
    @Rating DECIMAL(3,2) = NULL,
    @TotalReviews INT = NULL,
    
    -- Additional Fields
    @ProviderId INT = NULL,
    @CreatedBy INT = NULL,
    @ModifiedBy INT = NULL
AS
BEGIN
    SET NOCOUNT ON;
    
    -- INSERT Operation
    IF @Action = 'INSERT'
    BEGIN
        INSERT INTO [dbo].[Employees] (
            EmployeeCode,
            Serviceproviderid,
            FirstName,
            LastName,
            FullName,
            Email,
            PhoneNumber,
            AlternatePhone,
            ProfileImage,
            DateOfBirth,
            Gender,
            Address,
            City,
            State,
            ZipCode,
            Country,
            EmployeeType,
            Department,
            Position,
            JobTitle,
            ReportsTo,
            HireDate,
            StartDate,
            EndDate,
            ProbationEndDate,
            WorkSchedule,
            DefaultStartTime,
            DefaultEndTime,
            WeeklyHours,
            IsFlexibleSchedule,
            PayType,
            PayRate,
            Currency,
            BankAccountNumber,
            BankRoutingNumber,
            Skills,
            Certifications,
            Specializations,
            Languages,
            YearsOfExperience,
            Bio,
            AssignedServices,
            AssignedLocations,
            MaxDailyAppointments,
            CanAcceptNewClients,
            UserId,
            Role,
            Permissions,
            CanManageOwnSchedule,
            CanViewReports,
            CanManageClients,
            LastLoginDate,
            IdDocumentUrl,
            IdDocumentVerified,
            BackgroundCheckStatus,
            BackgroundCheckDate,
            EmergencyContactName,
            EmergencyContactPhone,
            EmergencyContactRelation,
            Status,
            StatusReason,
            Notes,
            Rating,
            TotalReviews,
            ProviderId,
            CreatedBy,
            CreatedDate,
            ModifiedBy,
            ModifiedDate
        )
        VALUES (
            @EmployeeCode,
            @Serviceproviderid,
            @FirstName,
            @LastName,
            @FullName,
            @Email,
            @PhoneNumber,
            @AlternatePhone,
            @ProfileImage,
            @DateOfBirth,
            @Gender,
            @Address,
            @City,
            @State,
            @ZipCode,
            @Country,
            @EmployeeType,
            @Department,
            @Position,
            @JobTitle,
            @ReportsTo,
            @HireDate,
            @StartDate,
            @EndDate,
            @ProbationEndDate,
            @WorkSchedule,
            @DefaultStartTime,
            @DefaultEndTime,
            @WeeklyHours,
            @IsFlexibleSchedule,
            @PayType,
            @PayRate,
            @Currency,
            @BankAccountNumber,
            @BankRoutingNumber,
            @Skills,
            @Certifications,
            @Specializations,
            @Languages,
            @YearsOfExperience,
            @Bio,
            @AssignedServices,
            @AssignedLocations,
            @MaxDailyAppointments,
            @CanAcceptNewClients,
            @UserId,
            @Role,
            @Permissions,
            @CanManageOwnSchedule,
            @CanViewReports,
            @CanManageClients,
            @LastLoginDate,
            @IdDocumentUrl,
            @IdDocumentVerified,
            @BackgroundCheckStatus,
            @BackgroundCheckDate,
            @EmergencyContactName,
            @EmergencyContactPhone,
            @EmergencyContactRelation,
            @Status,
            @StatusReason,
            @Notes,
            @Rating,
            @TotalReviews,
            @ProviderId,
            @CreatedBy,
            GETUTCDATE(),
            @ModifiedBy,
            GETUTCDATE()
        );
        
        -- Return the new employee ID
        SELECT SCOPE_IDENTITY() AS NewEmployeeId;
    END
    
    -- UPDATE Operation
    ELSE IF @Action = 'UPDATE'
    BEGIN
        UPDATE [dbo].[Employees]
        SET
            EmployeeCode        = ISNULL(@EmployeeCode, EmployeeCode),
            Serviceproviderid   = ISNULL(@Serviceproviderid, Serviceproviderid),
            FirstName           = ISNULL(@FirstName, FirstName),
            LastName            = ISNULL(@LastName, LastName),
            FullName            = ISNULL(@FullName, FullName),
            Email               = ISNULL(@Email, Email),
            PhoneNumber         = ISNULL(@PhoneNumber, PhoneNumber),
            AlternatePhone      = ISNULL(@AlternatePhone, AlternatePhone),
            ProfileImage        = ISNULL(@ProfileImage, ProfileImage),
            DateOfBirth         = ISNULL(@DateOfBirth, DateOfBirth),
            Gender              = ISNULL(@Gender, Gender),
            Address             = ISNULL(@Address, Address),
            City                = ISNULL(@City, City),
            State               = ISNULL(@State, State),
            ZipCode             = ISNULL(@ZipCode, ZipCode),
            Country             = ISNULL(@Country, Country),
            EmployeeType        = ISNULL(@EmployeeType, EmployeeType),
            Department          = ISNULL(@Department, Department),
            Position            = ISNULL(@Position, Position),
            JobTitle            = ISNULL(@JobTitle, JobTitle),
            ReportsTo           = ISNULL(@ReportsTo, ReportsTo),
            HireDate            = ISNULL(@HireDate, HireDate),
            StartDate           = ISNULL(@StartDate, StartDate),
            EndDate             = ISNULL(@EndDate, EndDate),
            ProbationEndDate    = ISNULL(@ProbationEndDate, ProbationEndDate),
            WorkSchedule        = ISNULL(@WorkSchedule, WorkSchedule),
            DefaultStartTime    = ISNULL(@DefaultStartTime, DefaultStartTime),
            DefaultEndTime      = ISNULL(@DefaultEndTime, DefaultEndTime),
            WeeklyHours         = ISNULL(@WeeklyHours, WeeklyHours),
            IsFlexibleSchedule  = ISNULL(@IsFlexibleSchedule, IsFlexibleSchedule),
            PayType             = ISNULL(@PayType, PayType),
            PayRate             = ISNULL(@PayRate, PayRate),
            Currency            = ISNULL(@Currency, Currency),
            BankAccountNumber   = ISNULL(@BankAccountNumber, BankAccountNumber),
            BankRoutingNumber   = ISNULL(@BankRoutingNumber, BankRoutingNumber),
            Skills              = ISNULL(@Skills, Skills),
            Certifications      = ISNULL(@Certifications, Certifications),
            Specializations     = ISNULL(@Specializations, Specializations),
            Languages           = ISNULL(@Languages, Languages),
            YearsOfExperience   = ISNULL(@YearsOfExperience, YearsOfExperience),
            Bio                 = ISNULL(@Bio, Bio),
            AssignedServices    = ISNULL(@AssignedServices, AssignedServices),
            AssignedLocations   = ISNULL(@AssignedLocations, AssignedLocations),
            MaxDailyAppointments= ISNULL(@MaxDailyAppointments, MaxDailyAppointments),
            CanAcceptNewClients = ISNULL(@CanAcceptNewClients, CanAcceptNewClients),
            UserId              = ISNULL(@UserId, UserId),
            Role                = ISNULL(@Role, Role),
            Permissions         = ISNULL(@Permissions, Permissions),
            CanManageOwnSchedule= ISNULL(@CanManageOwnSchedule, CanManageOwnSchedule),
            CanViewReports      = ISNULL(@CanViewReports, CanViewReports),
            CanManageClients    = ISNULL(@CanManageClients, CanManageClients),
            LastLoginDate       = ISNULL(@LastLoginDate, LastLoginDate),
            IdDocumentUrl       = ISNULL(@IdDocumentUrl, IdDocumentUrl),
            IdDocumentVerified  = ISNULL(@IdDocumentVerified, IdDocumentVerified),
            BackgroundCheckStatus   = ISNULL(@BackgroundCheckStatus, BackgroundCheckStatus),
            BackgroundCheckDate     = ISNULL(@BackgroundCheckDate, BackgroundCheckDate),
            EmergencyContactName    = ISNULL(@EmergencyContactName, EmergencyContactName),
            EmergencyContactPhone   = ISNULL(@EmergencyContactPhone, EmergencyContactPhone),
            EmergencyContactRelation= ISNULL(@EmergencyContactRelation, EmergencyContactRelation),
            Status              = ISNULL(@Status, Status),
            StatusReason        = ISNULL(@StatusReason, StatusReason),
            Notes               = ISNULL(@Notes, Notes),
            Rating              = ISNULL(@Rating, Rating),
            TotalReviews        = ISNULL(@TotalReviews, TotalReviews),
            ProviderId          = ISNULL(@ProviderId, ProviderId),
            ModifiedBy          = @ModifiedBy,
            ModifiedDate        = GETUTCDATE()
        WHERE Id = @Id;

        SELECT 'Updated Successfully' AS Message;
    END
    
    -- DELETE Operation
    ELSE IF @Action = 'DELETE'
    BEGIN
        DELETE FROM [dbo].[Employees]
        WHERE Id = @Id;
        
        SELECT 'Deleted Successfully' AS Message;
    END
    
    -- GET BY ID Operation
    ELSE IF @Action = 'GETBYID'
    BEGIN
        SELECT 
            Id,
            EmployeeCode,
            Serviceproviderid,
            FirstName,
            LastName,
            FullName,
            Email,
            PhoneNumber,
            AlternatePhone,
            ProfileImage,
            DateOfBirth,
            Gender,
            Address,
            City,
            State,
            ZipCode,
            Country,
            EmployeeType,
            Department,
            Position,
            JobTitle,
            ReportsTo,
            HireDate,
            StartDate,
            EndDate,
            ProbationEndDate,
            WorkSchedule,
            DefaultStartTime,
            DefaultEndTime,
            WeeklyHours,
            IsFlexibleSchedule,
            PayType,
            PayRate,
            Currency,
            BankAccountNumber,
            BankRoutingNumber,
            Skills,
            Certifications,
            Specializations,
            Languages,
            YearsOfExperience,
            Bio,
            AssignedServices,
            AssignedLocations,
            MaxDailyAppointments,
            CanAcceptNewClients,
            UserId,
            Role,
            Permissions,
            CanManageOwnSchedule,
            CanViewReports,
            CanManageClients,
            LastLoginDate,
            IdDocumentUrl,
            IdDocumentVerified,
            BackgroundCheckStatus,
            BackgroundCheckDate,
            EmergencyContactName,
            EmergencyContactPhone,
            EmergencyContactRelation,
            Status,
            StatusReason,
            Notes,
            Rating,
            TotalReviews,
            ProviderId,
            CreatedBy,
            CreatedDate,
            ModifiedBy,
            ModifiedDate
        FROM [dbo].[Employees]
        WHERE Id = @Id;
    END
    
    -- GET ALL Operation
    ELSE IF @Action = 'GETALL'
    BEGIN
        SELECT
            Id,
            EmployeeCode,
            Serviceproviderid,
            FirstName,
            LastName,
            FullName,
            Email,
            PhoneNumber,
            AlternatePhone,
            ProfileImage,
            DateOfBirth,
            Gender,
            Address,
            City,
            State,
            ZipCode,
            Country,
            EmployeeType,
            Department,
            Position,
            JobTitle,
            ReportsTo,
            HireDate,
            StartDate,
            EndDate,
            ProbationEndDate,
            WorkSchedule,
            DefaultStartTime,
            DefaultEndTime,
            WeeklyHours,
            IsFlexibleSchedule,
            PayType,
            PayRate,
            Currency,
            BankAccountNumber,
            BankRoutingNumber,
            Skills,
            Certifications,
            Specializations,
            Languages,
            YearsOfExperience,
            Bio,
            AssignedServices,
            AssignedLocations,
            MaxDailyAppointments,
            CanAcceptNewClients,
            UserId,
            Role,
            Permissions,
            CanManageOwnSchedule,
            CanViewReports,
            CanManageClients,
            LastLoginDate,
            IdDocumentUrl,
            IdDocumentVerified,
            BackgroundCheckStatus,
            BackgroundCheckDate,
            EmergencyContactName,
            EmergencyContactPhone,
            EmergencyContactRelation,
            Status,
            StatusReason,
            Notes,
            Rating,
            TotalReviews,
            ProviderId,
            CreatedBy,
            CreatedDate,
            ModifiedBy,
            ModifiedDate
        FROM [dbo].[Employees]
        ORDER BY CreatedDate DESC;
    END

    -- GET BY SERVICE PROVIDER ID Operation
    ELSE IF @Action = 'GETBYSERVICEPROVIDERID'
    BEGIN
        SELECT
            Id,
            EmployeeCode,
            Serviceproviderid,
            FirstName,
            LastName,
            FullName,
            Email,
            PhoneNumber,
            AlternatePhone,
            ProfileImage,
            DateOfBirth,
            Gender,
            Address,
            City,
            State,
            ZipCode,
            Country,
            EmployeeType,
            Department,
            Position,
            JobTitle,
            ReportsTo,
            HireDate,
            StartDate,
            EndDate,
            ProbationEndDate,
            WorkSchedule,
            DefaultStartTime,
            DefaultEndTime,
            WeeklyHours,
            IsFlexibleSchedule,
            PayType,
            PayRate,
            Currency,
            BankAccountNumber,
            BankRoutingNumber,
            Skills,
            Certifications,
            Specializations,
            Languages,
            YearsOfExperience,
            Bio,
            AssignedServices,
            AssignedLocations,
            MaxDailyAppointments,
            CanAcceptNewClients,
            UserId,
            Role,
            Permissions,
            CanManageOwnSchedule,
            CanViewReports,
            CanManageClients,
            LastLoginDate,
            IdDocumentUrl,
            IdDocumentVerified,
            BackgroundCheckStatus,
            BackgroundCheckDate,
            EmergencyContactName,
            EmergencyContactPhone,
            EmergencyContactRelation,
            Status,
            StatusReason,
            Notes,
            Rating,
            TotalReviews,
            ProviderId,
            CreatedBy,
            CreatedDate,
            ModifiedBy,
            ModifiedDate
        FROM [dbo].[Employees]
        WHERE Serviceproviderid = @Serviceproviderid
        ORDER BY CreatedDate DESC;
    END
END
GO

-- =============================================
-- Table Creation Script (if table doesn't exist)
-- =============================================

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Employees]') AND type in (N'U'))
BEGIN
    CREATE TABLE [dbo].[Employees] (
        Id INT IDENTITY(1,1) PRIMARY KEY,
        EmployeeCode NVARCHAR(20) NULL,
        Serviceproviderid NVARCHAR(20) NULL,
        FirstName NVARCHAR(100) NULL,
        LastName NVARCHAR(100) NULL,
        FullName NVARCHAR(200) NULL,
        Email NVARCHAR(256) NULL,
        PhoneNumber NVARCHAR(20) NULL,
        AlternatePhone NVARCHAR(20) NULL,
        ProfileImage NVARCHAR(1000) NULL,
        DateOfBirth DATE NULL,
        Gender NVARCHAR(20) NULL,
        Address NVARCHAR(500) NULL,
        City NVARCHAR(100) NULL,
        State NVARCHAR(100) NULL,
        ZipCode NVARCHAR(20) NULL,
        Country NVARCHAR(100) NULL,
        EmployeeType NVARCHAR(50) NULL,
        Department NVARCHAR(100) NULL,
        Position NVARCHAR(100) NULL,
        JobTitle NVARCHAR(100) NULL,
        ReportsTo INT NULL,
        HireDate DATE NULL,
        StartDate DATE NULL,
        EndDate DATE NULL,
        ProbationEndDate DATE NULL,
        WorkSchedule NVARCHAR(MAX) NULL,
        DefaultStartTime TIME NULL,
        DefaultEndTime TIME NULL,
        WeeklyHours DECIMAL(5,2) NULL,
        IsFlexibleSchedule BIT NULL,
        PayType NVARCHAR(20) NULL,
        PayRate DECIMAL(10,2) NULL,
        Currency NVARCHAR(10) NULL,
        BankAccountNumber NVARCHAR(50) NULL,
        BankRoutingNumber NVARCHAR(50) NULL,
        Skills NVARCHAR(MAX) NULL,
        Certifications NVARCHAR(MAX) NULL,
        Specializations NVARCHAR(MAX) NULL,
        Languages NVARCHAR(500) NULL,
        YearsOfExperience INT NULL,
        Bio NVARCHAR(1000) NULL,
        AssignedServices NVARCHAR(MAX) NULL,
        AssignedLocations NVARCHAR(MAX) NULL,
        MaxDailyAppointments INT NULL,
        CanAcceptNewClients BIT NULL,
        UserId INT NULL,
        Role NVARCHAR(50) NULL,
        Permissions NVARCHAR(MAX) NULL,
        CanManageOwnSchedule BIT NULL,
        CanViewReports BIT NULL,
        CanManageClients BIT NULL,
        LastLoginDate DATETIMEOFFSET NULL,
        IdDocumentUrl NVARCHAR(1000) NULL,
        IdDocumentVerified BIT NULL,
        BackgroundCheckStatus NVARCHAR(50) NULL,
        BackgroundCheckDate DATE NULL,
        EmergencyContactName NVARCHAR(200) NULL,
        EmergencyContactPhone NVARCHAR(20) NULL,
        EmergencyContactRelation NVARCHAR(50) NULL,
        Status NVARCHAR(50) NULL,
        StatusReason NVARCHAR(500) NULL,
        Notes NVARCHAR(MAX) NULL,
        Rating DECIMAL(3,2) NULL,
        TotalReviews INT NULL,
        ProviderId INT NULL,
        CreatedBy INT NULL,
        CreatedDate DATETIMEOFFSET NULL,
        ModifiedBy INT NULL,
        ModifiedDate DATETIMEOFFSET NULL
    );
    
    -- Create indexes for better performance
    CREATE INDEX IX_Employees_Email ON Employees(Email);
    CREATE INDEX IX_Employees_ServiceProviderId ON Employees(Serviceproviderid);
    CREATE INDEX IX_Employees_Status ON Employees(Status);
    CREATE INDEX IX_Employees_Role ON Employees(Role);
END
GO

PRINT 'Stored procedure sp_Employees_CRUD created successfully.';
PRINT 'Employees table checked/created successfully.';
GO
