// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using vestshed.Data;

#nullable disable

namespace vestshed.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("vestshed.Models.PetInvoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amount")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Amount");

                    b.Property<decimal?>("AnyTip")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("AnyTip");

                    b.Property<string>("CareNotes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CareNotes");

                    b.Property<decimal?>("DepositPercentage")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("DepositPercentage");

                    b.Property<string>("Items")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Items");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int")
                        .HasColumnName("LocationId");

                    b.Property<string>("PaymentTerms")
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("PaymentTerms");

                    b.Property<int?>("PetParentId")
                        .HasColumnType("int")
                        .HasColumnName("PetParentId");

                    b.Property<string>("Quantity")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Quantity");

                    b.Property<int?>("ServiceProviderId")
                        .HasColumnType("int")
                        .HasColumnName("ServiceProviderId");

                    b.HasKey("Id");

                    b.ToTable("PetInvoice");
                });
#pragma warning restore 612, 618
        }
    }
}
