using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using vestshed.Data;
using vestshed.Models;

namespace vestshed.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    [AllowAnonymous]
    public class ProviderOnboardingController : ControllerBase
    {
        private readonly ApplicationDbContext _context;
        private readonly ILogger<ProviderOnboardingController> _logger;

        public ProviderOnboardingController(ApplicationDbContext context, ILogger<ProviderOnboardingController> logger)
        {
            _context = context;
            _logger = logger;
        }

        /// <summary>
        /// Test database connection
        /// </summary>
        [HttpGet("test-connection")]
        public async Task<ActionResult> TestConnection()
        {
            try
            {
                var canConnect = await _context.Database.CanConnectAsync();
                if (canConnect)
                {
                    return Ok(new { success = true, message = "Database connection successful" });
                }
                else
                {
                    return StatusCode(500, new { success = false, message = "Cannot connect to database" });
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Database connection test failed");
                return StatusCode(500, new { success = false, message = $"Database connection failed: {ex.Message}" });
            }
        }

        /// <summary>
        /// Insert provider onboarding data from JSON into database using stored procedure
        /// </summary>
        /// <param name="request">Provider onboarding data</param>
        /// <returns>ProviderId generated by stored procedure</returns>
        [HttpPost("insert")]
        public async Task<ActionResult<ProviderOnboardingTempResponse>> InsertProviderOnboarding([FromBody] ProviderOnboardingTempRequest request)
        {
            try
            {
                if (request == null)
                {
                    return BadRequest(new ProviderOnboardingTempResponse
                    {
                        Success = false,
                        Message = "Request body cannot be null"
                    });
                }

                // Validate required fields
                if (string.IsNullOrWhiteSpace(request.Email))
                {
                    return BadRequest(new ProviderOnboardingTempResponse
                    {
                        Success = false,
                        Message = "Email is required"
                    });
                }

                // Call stored procedure through DbContext
                _logger.LogInformation("Attempting to insert provider onboarding data for Email: {Email}", request.Email);
                
                var providerId = await _context.InsertProviderOnboardingTempAsync(request);

                if (string.IsNullOrEmpty(providerId))
                {
                    _logger.LogWarning("Stored procedure executed but no ProviderId was returned");
                    return StatusCode(500, new ProviderOnboardingTempResponse
                    {
                        Success = false,
                        Message = "Data insertion may have failed. No ProviderId was returned from stored procedure."
                    });
                }

                _logger.LogInformation("Successfully inserted provider onboarding data. ProviderId: {ProviderId}", providerId);

                return Ok(new ProviderOnboardingTempResponse
                {
                    ProviderId = providerId,
                    Success = true,
                    Message = "Provider onboarding data inserted successfully"
                });
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error inserting provider onboarding data. Inner Exception: {InnerException}", ex.InnerException?.Message);
                var errorMessage = ex.InnerException != null 
                    ? $"{ex.Message} Inner Exception: {ex.InnerException.Message}" 
                    : ex.Message;
                
                return StatusCode(500, new ProviderOnboardingTempResponse
                {
                    Success = false,
                    Message = $"An error occurred: {errorMessage}"
                });
            }
        }

        /// <summary>
        /// Insert multiple provider onboarding records from JSON array
        /// </summary>
        /// <param name="requests">Array of provider onboarding data</param>
        /// <returns>List of ProviderIds generated by stored procedure</returns>
        [HttpPost("insert-batch")]
        public async Task<ActionResult<List<ProviderOnboardingTempResponse>>> InsertProviderOnboardingBatch([FromBody] List<ProviderOnboardingTempRequest> requests)
        {
            try
            {
                if (requests == null || requests.Count == 0)
                {
                    return BadRequest(new List<ProviderOnboardingTempResponse>
                    {
                        new ProviderOnboardingTempResponse
                        {
                            Success = false,
                            Message = "Request body cannot be null or empty"
                        }
                    });
                }

                var responses = new List<ProviderOnboardingTempResponse>();

                foreach (var request in requests)
                {
                    try
                    {
                        var providerId = await _context.InsertProviderOnboardingTempAsync(request);
                        responses.Add(new ProviderOnboardingTempResponse
                        {
                            ProviderId = providerId,
                            Success = true,
                            Message = "Provider onboarding data inserted successfully"
                        });
                    }
                    catch (Exception ex)
                    {
                        _logger.LogError(ex, "Error inserting provider onboarding data for request with Email: {Email}", request.Email);
                        responses.Add(new ProviderOnboardingTempResponse
                        {
                            Success = false,
                            Message = $"Error inserting record with Email {request.Email}: {ex.Message}"
                        });
                    }
                }

                return Ok(responses);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error in batch insert");
                return StatusCode(500, new List<ProviderOnboardingTempResponse>
                {
                    new ProviderOnboardingTempResponse
                    {
                        Success = false,
                        Message = $"An error occurred: {ex.Message}"
                    }
                });
            }
        }

        /// <summary>
        /// Move provider onboarding data from temp table to final table using stored procedure
        /// </summary>
        /// <param name="request">Move provider onboarding request with TempProviderId and optional additional data</param>
        /// <returns>New ProviderId generated by stored procedure</returns>
        [HttpPost("move")]
        public async Task<ActionResult<MoveProviderOnboardingResponse>> MoveProviderOnboarding([FromBody] MoveProviderOnboardingRequest request)
        {
            try
            {
                if (request == null)
                {
                    return BadRequest(new MoveProviderOnboardingResponse
                    {
                        Success = false,
                        Message = "Request body cannot be null"
                    });
                }

                // Validate required field
                if (string.IsNullOrWhiteSpace(request.TempProviderId))
                {
                    return BadRequest(new MoveProviderOnboardingResponse
                    {
                        Success = false,
                        Message = "TempProviderId is required"
                    });
                }

                // Call stored procedure through DbContext
                _logger.LogInformation("Attempting to move provider onboarding data for TempProviderId: {TempProviderId}", request.TempProviderId);
                
                var newProviderId = await _context.MoveProviderOnboardingAsync(request);

                if (string.IsNullOrEmpty(newProviderId))
                {
                    _logger.LogWarning("Stored procedure executed but no NewProviderId was returned for TempProviderId: {TempProviderId}", request.TempProviderId);
                    return StatusCode(500, new MoveProviderOnboardingResponse
                    {
                        Success = false,
                        Message = "Data move operation may have failed. No NewProviderId was returned from stored procedure."
                    });
                }

                _logger.LogInformation("Successfully moved provider onboarding data. NewProviderId: {NewProviderId}", newProviderId);

                return Ok(new MoveProviderOnboardingResponse
                {
                    NewProviderId = newProviderId,
                    Success = true,
                    Message = "Provider onboarding data moved successfully from temp table to final table"
                });
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error moving provider onboarding data. Inner Exception: {InnerException}", ex.InnerException?.Message);
                var errorMessage = ex.InnerException != null 
                    ? $"{ex.Message} Inner Exception: {ex.InnerException.Message}" 
                    : ex.Message;
                
                return StatusCode(500, new MoveProviderOnboardingResponse
                {
                    Success = false,
                    Message = $"An error occurred: {errorMessage}"
                });
            }
        }
    }
}


